# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhoneBooth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneBooth
  pod 'SwiftLint'

  target 'PhoneBoothTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhoneBoothUITests' do
    # Pods for testing
  end

end
